name: Run GCP Test Suite

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc curl

      - name: Make test suite executable
        run: chmod +x ./gcp-test-suite.sh

      - name: Run test suite
        run: ./gcp-test-suite.sh --run-all
