name: Run GCP Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout protection

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc curl
        continue-on-error: false

      - name: Make test suite executable
        run: chmod +x ./gcp-test-suite.sh

      - name: Run test suite
        run: ./gcp-test-suite.sh --run-all
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        timeout-minutes: 15
